import {
  ArrowUp as ArrowUpIcon,
  Paperclip as AttachmentIcon,
  Bot as BotIcon,
  Box as BoxIcon,
  CheckCircle as CheckCircleFillIcon,
  Square as CheckedSquare, // Approximation
  ChevronDown as ChevronDownIcon,
  History as ClockRewind, // Approximation
  Code as CodeIcon,
  Copy as CopyIcon,
  Cpu as CpuIcon,
  X as CrossIcon,
  X as CrossSmallIcon,
  Triangle as DeltaIcon, // Approximation
  Download as DownloadIcon,
  Eye as EyeIcon,
  File as FileIcon,
  Maximize as FullscreenIcon,
  GitBranch as GitIcon, // Approximation
  Globe as GlobeIcon,
  MapPin as GPSIcon,
  Home as HomeIcon,
  Image as ImageIcon,
  Info as InfoIcon,
  FileText as InvoiceIcon, // Approximation
  LineChart as LineChartIcon,
  Loader as LoaderIcon,
  Lock as LockIcon,
  // Logos are not in lucide-react, define simple SVGs or skip
  FileText as LogsIcon, // Approximation
  Menu as MenuIcon,
  MessageSquare as MessageIcon,
  MoreHorizontal as MoreHorizontalIcon,
  MoreHorizontal as MoreIcon, // Approximation
  Paperclip as PaperclipIcon,
  Edit as PencilEditIcon,
  Pen as PenIcon,
  Play as PlayIcon,
  Plus as PlusIcon,
  // PythonIcon not in lucide
  Redo as RedoIcon,
  Route as RouteIcon,
  Share as ShareIcon,
  Sidebar as SidebarLeftIcon,
  Sparkles as SparklesIcon,
  Square as StopIcon, // Approximation
  FileText as SummarizeIcon, // Approximation
  Terminal as TerminalIcon,
  Terminal as TerminalWindowIcon,
  ThumbsDown as ThumbDownIcon,
  ThumbsUp as ThumbUpIcon,
  Trash as TrashIcon,
  Square as UncheckedSquare,
  Undo as UndoIcon,
  Upload as UploadIcon,
  User as UserIcon,
  // VercelIcon not in lucide
  AlertTriangle as WarningIcon,
} from "lucide-react";

export const LogoAnthropic = () => <span>Anthropic</span>;
export const LogoGoogle = () => <span>Google</span>;
export const LogoOpenAI = () => <span>OpenAI</span>;
export const PythonIcon = () => <span>Python</span>;
export const VercelIcon = () => <span>Vercel</span>;

export {
  ArrowUpIcon,
  AttachmentIcon,
  BotIcon,
  BoxIcon,
  CheckCircleFillIcon,
  CheckedSquare,
  ChevronDownIcon,
  ClockRewind,
  CodeIcon,
  CopyIcon,
  CpuIcon,
  CrossIcon,
  CrossSmallIcon,
  DeltaIcon,
  DownloadIcon,
  EyeIcon,
  FileIcon,
  FullscreenIcon,
  GitIcon,
  GlobeIcon,
  GPSIcon,
  HomeIcon,
  ImageIcon,
  InfoIcon,
  InvoiceIcon,
  LineChartIcon,
  LoaderIcon,
  LockIcon,
  LogsIcon,
  MenuIcon,
  MessageIcon,
  MoreHorizontalIcon,
  MoreIcon,
  PaperclipIcon,
  PencilEditIcon,
  PenIcon,
  PlayIcon,
  PlusIcon,
  RedoIcon,
  RouteIcon,
  ShareIcon,
  SidebarLeftIcon,
  SparklesIcon,
  StopIcon,
  SummarizeIcon,
  TerminalIcon,
  TerminalWindowIcon,
  ThumbDownIcon,
  ThumbUpIcon,
  TrashIcon,
  UncheckedSquare,
  UndoIcon,
  UploadIcon,
  UserIcon,
  WarningIcon,
};
