export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

/**
 * Root layout for the login page.
 *
 * @param { { children: React.ReactNode } } props - The component props.
 * @param {React.ReactNode} props.children - The child components to render.
 * @returns {JSX.Element} The rendered root layout.
 */
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
